version: 2
sources:
  - name: gcs_raw
    database: "{{ target.project }}"
    schema: bookstore_src
    tables:
      - name: ext_customers
      - name: ext_transactions
      - name: ext_transactions_recurrent
        external:
          location: 'gs://modern-data-stack-msp-uam-2026-lab-workspace/data-lake/raw-data/transactions_recurrent/*'
          options:
            format: 'JSON'
            hive_partition_uri_prefix: 'gs://modern-data-stack-msp-uam-2026-lab-workspace/data-lake/raw-data/transactions_recurrent/'
          partitions:
            - name: date
              data_type: date
      - name: ext_books
        external:
          location: 'gs://TWOJ_BUCKET/books.csv' # Podaj swoją ścieżkę
          options:
            format: 'CSV'
            skip_leading_rows: 1
            encoding: 'UTF-8'
            allow_quoted_newlines: true